name: oivan_task
description: "A Flutter application that explores StackOverflow users using the StackExchange public APIs. The app demonstrates clean architecture principles, modern state management, and scalable project structure."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management & DI
  flutter_riverpod: ^3.0.3

  # Networking
  dio: ^5.4.0

  # Navigation
  go_router: ^17.0.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Models & State
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Utilities
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1


flutter:

  uses-material-design: true
  assets:
    - assets/images/

